name: Build Alpine Caddy Cloudflare DNS Image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Caddy version
        required: true

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: RELEASE_VERSION=${{ github.event.inputs.release_version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/neilbartley/caddy-cloudflare:latest
            ghcr.io/neilbartley/caddy-cloudflare:${{ github.event.inputs.release_version }}
          labels: |
            org.opencontainers.image.title=Caddy Cloudflare
            org.opencontainers.image.description=Docker for caddy-cloudflare - forked from Technoguyfication/caddy-cloudflare
            org.opencontainers.image.url=https://github.com/neilbartley/caddy-cloudflare/pkgs/container/caddy-cloudflare/
